language: node_js
node_js:
  - "node"

install:
  - npm install
  - export PORT=8080
  - npm install socket.io-client
  
services:
  - mysql
  
before_script:
  - mysql -e 'create database c9;'
  - mysql -u root -h localhost c9 < dump_mysql.sql 
  
